### ISSUE TITLE
GPU leaks memory

### ISSUE THREAD

**Issue by mmerayo** [jdermody/brightwire#26]
See following log generated from a small batch when predicting. It happened after hours of working fine.. 
{ "Severity": "ERROR", "Src": "Framework.Core.CQRS.Commands.Handlers.DomainCommandHandler`1+<ExecuteAsync>d__5.MoveNext", "Device": "WORKING", "AppName": "Invoices importer", "AppVersion": "1.0.0.0", "AppInstanceId": "1", "ThreadId": "1", "Index": "1", "SessionId": "2019-05-12_07:05", "Time": "2019-05-12 07:09:32.3390", "Detail": "OrchestrationId:16d97dee-504f-4c1f-a882-c6c553620d30 - TimeTaken:00:00:18.5047864 - System.Exception: ErrorOutOfMemory: CUDA_ERROR_OUT_OF_MEMORY-out of memory\r\n   at BrightWire.Cuda.Helper.DeviceMemory.Block.CheckForError(CUResult result) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\Helper\\DeviceMemory.cs:line 65\r\n   at BrightWire.Cuda.Helper.DeviceMemory.Block..ctor(DeviceMemory cache, Int32 index, Int32 size) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\Helper\\DeviceMemory.cs:line 43\r\n   at BrightWire.Cuda.Helper.DeviceMemory.GetMemory(Int32 size) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\Helper\\DeviceMemory.cs:line 229\r\n   at BrightWire.LinearAlgebra.CudaProvider.Allocate(Int32 size, Boolean setToZero) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\CudaProvider.cs:line 1171\r\n   at BrightWire.LinearAlgebra.CudaProvider.TanH(IDeviceMemoryPtr a, Int32 size) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\CudaProvider.cs:line 396\r\n   at BrightWire.LinearAlgebra.GpuMatrix.TanhActivation() in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.CUDA.Source\\GpuMatrix.cs:line 481\r\n   at BrightWire.ExecutionGraph.Activation.Tanh.ExecuteForward(IContext context) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Activation\\Tanh.cs:line 35\r\n   at BrightWire.ExecutionGraph.Node.NodeBase.ExecuteForward(IContext context, Int32 channel) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Node\\NodeBase.cs:line 104\r\n   at BrightWire.ExecutionGraph.Engine.Helper.ExecutionEngineContext.ExecuteNext() in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Engine\\Helper\\ExecutionEngineContext.cs:line 56\r\n   at BrightWire.ExecutionGraph.Engine.ExecutionEngine._Execute(IExecutionContext executionContext, IMiniBatch batch) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Engine\\ExecutionEngine.cs:line 99\r\n   at BrightWire.ExecutionGraph.Engine.ExecutionEngine.<>c__DisplayClass14_0.<Execute>b__0(IMiniBatch mb) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Engine\\ExecutionEngine.cs:line 56\r\n   at BrightWire.ExecutionGraph.Helper.MiniBatchProvider.MiniBatchOperation.Execute(IExecutionContext executionContext) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Helper\\MiniBatchProvider.cs:line 29\r\n   at BrightWire.ExecutionGraph.Engine.ExecutionEngine.Execute(IDataSource dataSource, Int32 batchSize, Action`1 batchCompleteCallback) in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\BrightWire.Source\\ExecutionGraph\\Engine\\ExecutionEngine.cs:line 63\r\n   at Crypto.Core.Domain.Prediction.Services.BrightWire.RnnDataPredictor.<>c__DisplayClass13_0.<Predict>b__0() in C:\\DEVELOPMENT\\SOLID\\Repositories\\saf\\src\\Crypto\\Crypto.WebApi\\Crypto.Core\\Domain\\Prediction\\Services\\BrightWire\\RnnDataPredictor.cs:line 123\r\n   at

**Comment by jdermody** [comment]
Is this a recurrent neural network? If so, it's possible that the sequence length is too long to fit in memory. Did you log the input that failed and is it any different from any of the successful inputs?

**Comment by jdermody** [comment]
BTW, you could try reducing the GPU memory cache size (or set it to zero)

**Comment by mmerayo** [comment]
Thank you so much, reduced the sequence and it works now. This library is awesome!
